language: ruby
sudo: false
rvm:
- 2.2.0
gemfile:
  - Gemfile
  - gemfiles/ohm-stateful-model-1.0.0.gem
  - gemfiles/ohm-zset-0.6.gem
deploy:
  provider: heroku
  api_key:
    secure: PlnTs96OkU7/yXFEsmyToSdpfN0c8WDZj7ERCaohMUQtjkNktXHzveXiJsxa/dhZNmcZnWDzEkPOCbqHEbLvsw3jE2xUCyLn1+CN/Od9xOF/uCaWhSXAAXOpg32VTu66en+HkP9L1N5sxsnVNno59uJR+lPGs5FvHn2vd9yuoQqn7skTl9xmgCi5UUn6uY+hkWNekdWuFm0DlOxaNzpgif9v5NcxuENpWOJxwkRhnO063u+MalQfdloOTaTBRTo7Hj+oPXnk1CHA8ESnW10LIqqocf48/JSXadrhTKare2KgErtZPIkVKeq7DtKZTOm1D82QYhRdhcSCHEoZ3K7fxWkl07DjLTi77+q1hw+r0CQoKkWqTHzcm5lh8sy6Zr+cvUx7K4dp6Ec7dMyM7mmy5HD/UbryNYkJozgieXji/rxLfuQL1pHtNzUw+v6KQqmegZTkg1IURpJf/uM1c9qTH2HqgJnEqiwHi/keXBwsXoRzK9V4TJZMGwT+ytY/UkmyStmJI8xcPmugny1H6J94ZmO6CAA6EQcJUODo64u38/IkFUVJsfVWFeoYJIDb2jmqWvda7vXE1dsswQVZojgb4bpnrV1UygTd0kyshQpQt860f9+rXK4uwrCNfR/NFXiHpz0LQRlo2vOvDOw4BzYySg5bDIDvJIxADxEahMHUkzs=
  app:
    master: assist-network-staging
    production: assist-network
  on:
    repo: AssistNetwork/an-backend
notifications:
  slack:
    secure: BDVEAjZXdLcddLOWG48IdRNGtYXcft4tUyJPUjdojxTKVoG0nySp5mOyApRng7uisgYtD+7FuHUcUh3xB7YcMP4ka7AwuGS2Vm5Ge10bM2t7CIj85aGgmLGbqO5/D3XNOuxXFgi+DrSKRFJlI7RcvMkOVYfmvfL7HUI4Ar7A6Kj6x9a+nKSR73NuniAR79Bx3YO7FoBn7K58Xkm36ukHXrg7qeXZX0ZJFd/wjtdkKAhGBpmWcRB80pPqcwVA3YL2qFjv/OlvEmx363tTdiIYO9fwJB779pUDm7vKhnF/QuXYrdOiaLklqY6SsJpxUDGeGRy5gbgK/YE8YmxVmvTUyiTcfyKHCD6E9Zcu5LhpjwcPBPR877JahBJyHekeUOTWp9IXznrU9oMjtrgofJDZMXHt112IXufSh3QRAKeOjNrL5E6oGMvAe/UTbpoq9OToXKFMxM2F4vFIT6fmD/sWrOv7nuOzGacDApxiCOqd+lvEcAsfZmmrrFhj1PjVr9b/rQEeONSY26nwKbSBpZNgGloxUHFs8oT6wgHzIziwZ3QQwtw8DWnoQaGlmYNKp6KuJPBoKw4N69ziPHK3q7/t6b3iCpHoB44ydwSDYQWqV6MyEeTwHihNp42VxJXUrXEU2WbtSKWhN6T3Z5Ov5cVwRVRsIDrNPSFB8g9k9ylFZsg=
bundler_args: --without development production
